# Generated by Django 3.2.8 on 2022-11-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='code',
            field=models.CharField(default='RWM4pkGIzX', max_length=10, unique=True),
        ),
    ]
