# Generated by Django 3.2.8 on 2022-11-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_bar_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='code',
            field=models.CharField(default='0fJfR1C9zX', max_length=10, unique=True),
        ),
    ]
